//! Per-project lua-language-server type generation.
//!
//! [`write_project`] emits three files into a project directory (the folder that
//! holds its `init.lua`):
//!
//! - `.luals/agentd.lua`  — the static stub for the fixed `agentd.*` / `ctx.*`
//!   API surface ([`STATIC_STUB`], hand-maintained in `assets/agentd.lua.stub`;
//!   the `.lua.stub` extension keeps lua-language-server from parsing the source
//!   copy and flagging it as a duplicate of a generated `.luals/agentd.lua`).
//! - `.luals/project.lua` — generated `---@alias` unions of *this* project's
//!   registered action / runner / skill names, so editors autocomplete them.
//! - `.luarc.json`        — points lua-language-server at `.luals/` as a library.
//!   An existing file is merged, never clobbered.
//!
//! No `mlua` dependency: the daemon and the `agentctl` client both call this
//! with plain name lists (the daemon from its live registries, the CLI from the
//! `tools.list` / `runners.list` / `skills.list` WebSocket methods).

use std::path::Path;

use anyhow::{Context, Result};
use serde_json::{Value, json};
use walkdir::WalkDir;

/// Static LuaLS stub for the fixed agentd Lua API. Hand-maintained.
pub const STATIC_STUB: &str = include_str!("../assets/agentd.lua.stub");

/// The subdirectory (under the project root) the stubs are written to.
pub const LUALS_DIR: &str = ".luals";

/// Write the static stub, the generated catalog, and a merged `.luarc.json`
/// into `project_dir`.
pub fn write_project(
    project_dir: &Path,
    actions: &[String],
    runners: &[String],
    skills: &[String],
) -> Result<()> {
    let luals = project_dir.join(LUALS_DIR);
    std::fs::create_dir_all(&luals)
        .with_context(|| format!("could not create the `{}` directory", luals.display()))?;

    let agentd_path = luals.join("agentd.lua");
    std::fs::write(&agentd_path, STATIC_STUB)
        .with_context(|| format!("could not write `{}`", agentd_path.display()))?;

    let imports = scan_import_modules(project_dir);
    let project_path = luals.join("project.lua");
    std::fs::write(
        &project_path,
        render_catalog(actions, runners, skills, &imports),
    )
    .with_context(|| format!("could not write `{}`", project_path.display()))?;

    let luarc_path = project_dir.join(".luarc.json");
    let merged = merge_luarc(read_json(&luarc_path)?);
    std::fs::write(
        &luarc_path,
        format!("{}\n", serde_json::to_string_pretty(&merged)?),
    )
    .with_context(|| format!("could not write `{}`", luarc_path.display()))?;

    Ok(())
}

/// Render `project.lua`: alias unions for the project's own names plus the
/// `import` function with one `---@overload` per project module that exports a
/// named `---@class`, so `import("tools/git.lua")` resolves to that module type.
/// An empty alias list falls back to `string` so the alias stays a valid type.
fn render_catalog(
    actions: &[String],
    runners: &[String],
    skills: &[String],
    imports: &[ImportModule],
) -> String {
    let mut out = String::from(
        "---@meta\n-- Generated by agentd: this project's registered names.\n-- Regenerated by `agentctl types` and on every `agentd --watch` reload.\n\n",
    );
    out.push_str(&alias("agentd.ActionName", actions));
    out.push_str(&alias("agentd.RunnerName", runners));
    out.push_str(&alias("agentd.SkillName", skills));
    out.push_str(&render_import(imports));
    out
}

/// One project module that `import(...)` can return: the path as written in
/// `import("...")` (relative to the project root, forward slashes) and the
/// `---@class` name it exports.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct ImportModule {
    path: String,
    class: String,
}

/// The `import` function definition with a typed overload per discovered module.
/// Paths that don't export a class fall through to the `---@return any` base.
fn render_import(imports: &[ImportModule]) -> String {
    let mut out = String::new();
    for m in imports {
        out.push_str(&format!(
            "---@overload fun(path: \"{}\"): {}\n",
            m.path.replace('\\', "\\\\").replace('"', "\\\""),
            m.class
        ));
    }
    out.push_str(
        "---Load a Lua file relative to the project root, or a bare package by name.\n---@param path string\n---@return any\nfunction import(path) end\n",
    );
    out
}

/// Walk the project directory for `*.lua` modules and, for each that ends in
/// `return <ident>` where `<ident>` is declared with a `---@class <Name>`,
/// record a path -> class mapping. `.luals/` is skipped (it's our own output).
fn scan_import_modules(project_dir: &Path) -> Vec<ImportModule> {
    let mut out = Vec::new();
    for entry in WalkDir::new(project_dir)
        .into_iter()
        .filter_entry(|e| e.file_name() != LUALS_DIR)
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("lua") {
            continue;
        }
        let Ok(rel) = path.strip_prefix(project_dir) else {
            continue;
        };
        let rel = rel.to_string_lossy().replace('\\', "/");
        let Ok(src) = std::fs::read_to_string(path) else {
            continue;
        };
        if let Some(class) = module_export_class(&src) {
            out.push(ImportModule { path: rel, class });
        }
    }
    out.sort();
    out
}

/// Detect a module's exported `---@class` name. Looks for the trailing
/// `return <ident>`, then the `---@class <Name>` annotation block immediately
/// above that ident's `local <ident> = ...` declaration. Returns `None` when the
/// module doesn't return a single annotated table.
fn module_export_class(src: &str) -> Option<String> {
    let lines: Vec<&str> = src.lines().collect();

    // Last top-level `return <ident>`.
    let ident = lines.iter().rev().find_map(|l| {
        let t = l.trim();
        let rest = t.strip_prefix("return ")?;
        let name = rest.trim();
        is_ident(name).then(|| name.to_string())
    })?;

    // The declaration line for that ident.
    let decl = format!("local {ident}");
    let decl_alt = format!("{ident} =");
    let decl_idx = lines
        .iter()
        .position(|l| l.trim_start().starts_with(&decl) || l.trim_start().starts_with(&decl_alt))?;

    // Walk up the contiguous `---` comment block above the declaration for a
    // `---@class <Name>` line.
    let mut i = decl_idx;
    while i > 0 {
        i -= 1;
        let t = lines[i].trim_start();
        if !t.starts_with("---") {
            break;
        }
        if let Some(rest) = t.strip_prefix("---@class ") {
            let name = rest.trim().trim_start_matches("(exact)").trim();
            let name = name.split([' ', ':']).next().unwrap_or("").trim();
            if is_ident_type(name) {
                return Some(name.to_string());
            }
        }
    }
    None
}

fn is_ident(s: &str) -> bool {
    !s.is_empty()
        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !s.chars().next().unwrap().is_ascii_digit()
}

/// Like [`is_ident`] but also allows dotted type names (e.g. `acme.Tool`).
fn is_ident_type(s: &str) -> bool {
    !s.is_empty() && s.split('.').all(is_ident)
}

fn alias(name: &str, names: &[String]) -> String {
    if names.is_empty() {
        return format!("---@alias {name} string\n\n");
    }
    let union = names
        .iter()
        .map(|n| format!("\"{}\"", n.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect::<Vec<_>>()
        .join("|");
    format!("---@alias {name} {union}\n\n")
}

fn read_json(path: &Path) -> Result<Value> {
    match std::fs::read_to_string(path) {
        Ok(s) if s.trim().is_empty() => Ok(json!({})),
        Ok(s) => serde_json::from_str(&s)
            .with_context(|| format!("`{}` exists but is not valid JSON", path.display())),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(json!({})),
        Err(e) => {
            Err(anyhow::Error::new(e).context(format!("could not read `{}`", path.display())))
        }
    }
}

/// Inject `.luals` into `workspace.library` and set a default `runtime.version`,
/// preserving every other key the user has.
fn merge_luarc(mut cfg: Value) -> Value {
    if !cfg.is_object() {
        cfg = json!({});
    }
    let obj = cfg.as_object_mut().unwrap();

    let lib = obj.entry("workspace.library").or_insert_with(|| json!([]));
    if !lib.is_array() {
        *lib = json!([]);
    }
    let arr = lib.as_array_mut().unwrap();
    let entry = json!(LUALS_DIR);
    if !arr.contains(&entry) {
        arr.push(entry);
    }

    obj.entry("runtime.version")
        .or_insert_with(|| json!("Lua 5.4"));

    cfg
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_three_files_into_fresh_dir() {
        let dir = tempfile::tempdir().unwrap();
        write_project(
            dir.path(),
            &["git.status".into(), "git.diff".into()],
            &["reviewer".into()],
            &["terse".into()],
        )
        .unwrap();

        let agentd = std::fs::read_to_string(dir.path().join(".luals/agentd.lua")).unwrap();
        assert!(agentd.contains("function agentd.action"));

        let project = std::fs::read_to_string(dir.path().join(".luals/project.lua")).unwrap();
        assert!(project.contains(r#"---@alias agentd.ActionName "git.status"|"git.diff""#));
        assert!(project.contains(r#"---@alias agentd.RunnerName "reviewer""#));
        assert!(project.contains(r#"---@alias agentd.SkillName "terse""#));

        let luarc: Value =
            serde_json::from_str(&std::fs::read_to_string(dir.path().join(".luarc.json")).unwrap())
                .unwrap();
        assert_eq!(luarc["workspace.library"], json!([".luals"]));
        assert_eq!(luarc["runtime.version"], json!("Lua 5.4"));
    }

    #[test]
    fn detects_exported_class() {
        let src = "---@class GitTool\n---@field status fun(): string\nlocal M = {}\nreturn M\n";
        assert_eq!(module_export_class(src).as_deref(), Some("GitTool"));
    }

    #[test]
    fn ignores_modules_without_returned_class() {
        // Side-effecting module (registers actions, returns nothing typed).
        let src = "agentd.action(\"git.status\", function() end)\n";
        assert_eq!(module_export_class(src), None);
        // Returns a table that has no class annotation.
        let src2 = "local M = {}\nreturn M\n";
        assert_eq!(module_export_class(src2), None);
    }

    #[test]
    fn emits_import_overload_for_module_with_class() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("tools")).unwrap();
        std::fs::write(
            dir.path().join("tools/git.lua"),
            "---@class GitTool\n---@field status fun(): string\nlocal M = {}\nreturn M\n",
        )
        .unwrap();
        // A side-effecting module gets no overload.
        std::fs::write(
            dir.path().join("tools/noop.lua"),
            "agentd.action(\"x\", function() end)\n",
        )
        .unwrap();

        write_project(dir.path(), &[], &[], &[]).unwrap();
        let project = std::fs::read_to_string(dir.path().join(".luals/project.lua")).unwrap();
        assert!(
            project.contains(r#"---@overload fun(path: "tools/git.lua"): GitTool"#),
            "missing git overload:\n{project}"
        );
        assert!(!project.contains("noop.lua"), "noop should be untyped");
        assert!(project.contains("function import(path) end"));
    }

    #[test]
    fn empty_lists_fall_back_to_string_alias() {
        let dir = tempfile::tempdir().unwrap();
        write_project(dir.path(), &[], &[], &[]).unwrap();
        let project = std::fs::read_to_string(dir.path().join(".luals/project.lua")).unwrap();
        assert!(project.contains("---@alias agentd.ActionName string"));
    }

    #[test]
    fn preserves_user_luarc_keys_and_dedupes_library() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join(".luarc.json"),
            r#"{ "diagnostics.globals": ["foo"], "workspace.library": [".luals", "vendor"] }"#,
        )
        .unwrap();

        write_project(dir.path(), &["a.b".into()], &[], &[]).unwrap();

        let luarc: Value =
            serde_json::from_str(&std::fs::read_to_string(dir.path().join(".luarc.json")).unwrap())
                .unwrap();
        // User key preserved.
        assert_eq!(luarc["diagnostics.globals"], json!(["foo"]));
        // `.luals` not duplicated; existing entries kept.
        assert_eq!(luarc["workspace.library"], json!([".luals", "vendor"]));
    }
}
